# Generated by Django 5.1.5 on 2025-01-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0002_booking_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="is_active",
        ),
    ]
