# Generated by Django 5.1.5 on 2025-02-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0003_remove_booking_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["number"]},
        ),
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("single", "Single"),
                    ("double", "Double"),
                    ("suite", "Suite"),
                    ("deluxe", "Deluxe"),
                ],
                max_length=50,
            ),
        ),
    ]
